### ISSUE TITLE
`print2tex` does not work with matrices which contains `missing`s

### ISSUE THREAD

**Issue by singularitti** [szcf-weiya/LaTeXTables.jl#8]
[This line](https://github.com/szcf-weiya/LaTeXTables.jl/blob/30bead5438be088359ba90cbdbd75f808821b2ac/src/tab2tex.jl#L180)
tests whether the item is a vector or a number. However, if a matrix contains `missing`s, since there is no method `length` defined for `missing`s, it cannot be executed.

If you want to test whether it is a `Number`, maybe use `x isa Number`?
Thank you!

**Comment by szcf-weiya** [comment]
Thanks! Do you have any suggestions for the `missing` values? I plan to add an argument to assign the missing entries, maybe just `missing` or `NA`.

**Comment by singularitti** [comment]
Hi @szcf-weiya, sorry for the late reply. I was pretty busy. I think maybe we just use `missing`s instead of `NaN`? Because `NaN` is always a floating point number in Julia while `missing` is of its own type. Here's the explanation from GPT-4:

```
`missing` and `NaN` are not equivalent in Julia.

`NaN` stands for "Not a Number" and is used to represent undefined or unrepresentable numerical results such as the result of 0/0. It's a special floating-point value.

`missing`, on the other hand, is used to represent missing or unknown values in data. It can be used with any type of data, not just numerical data.

So while they might be used in similar ways to represent "absence" of a value, they have different uses and are not the same.
```

**Comment by szcf-weiya** [comment]
Sorry for the late reply, I was also busy recently. 

It has been implemented in the above commit, and the new version v0.1.4 will be released.
